basePath: /
definitions:
  structs.Response:
    properties:
      code:
        type: integer
      message:
        type: string
      payload:
        type: object
    type: object
host: localhost:9999
info:
  contact: {}
  title: file-X Project API
  version: 0.0.2
paths:
  /ping:
    get:
      operationId: ping
      parameters:
      - description: key Request
        in: header
        name: key
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.Response'
        "400":
          description: Неверные данные
          schema:
            $ref: '#/definitions/structs.Response'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/structs.Response'
      summary: check service status
      tags:
      - Ping Service
swagger: "2.0"
